version: "3.9"

services:
    glovodeliveryapi:
        build: .
        container_name: glovo-delivery-api
        depends_on:
            - database
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mysql
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
        ports:
            - 8080:8080

    database:
        image: mysql
        container_name: database
        environment:
          - MYSQL_ROOT_USER=root
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=glovo
